# Travis CI instructions

sudo: required
dist: trusty
language: generic

notifications:
  email:
    on_failure: always
    recipients:
      - g.sansone@pilz.de
      - c.doehn@pilz.de
      - s.heinisch@pilz.de
env:
  global:
    - CATKIN_LINT=true
  matrix:
    - ROS_REPO=ros ROS_DISTRO="melodic"
    - ROS_REPO=testing ROS_DISTRO="melodic"
    - ROS_REPO=ros ROS_DISTRO="kinetic"
    - ROS_REPO=testing ROS_DISTRO="kinetic"
  allow_failures:
    - env: ROS_REPO=ros
  fast_finish: true
install:
  - git clone -b master --depth=1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh
